### ISSUE TITLE
toad/c_utils.pyx:40:9: 'number' is not a type identifier

### ISSUE THREAD

**Issue by momomobinx** [amphibian-dev/toad#103]
python 3.9

Cython 0.29.32

want toad==0.0.64

```
Collecting toad==0.0.64
  Downloading http://pypi.doubanio.com/packages/ff/ea/c710869ac054c425fd42668a36f6dd919ddd492afa2d369eedc388085ef2/toad-0.0.64.tar.gz (14.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 1.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [183 lines of output]
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cimport numpy as np
      cimport cython
      
      
      
      cdef number c_min(number[:] arr):
          ^
      ------------------------------------------------------------
      
      toad/c_utils.pyx:9:5: 'number' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cimport numpy as np
      cimport cython
      
      
      
      cdef number c_min(number[:] arr):
                       ^
      ------------------------------------------------------------
      
      toad/c_utils.pyx:9:18: 'number' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              if res > arr[i]:
                  res = arr[i]
          return res
      
      
      cdef number c_sum(number[:,:] arr):
          ^
      ------------------------------------------------------------
      
      toad/c_utils.pyx:18:5: 'number' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              if res > arr[i]:
                  res = arr[i]
          return res
      
      
      cdef number c_sum(number[:,:] arr):
                       ^
      ------------------------------------------------------------
      
      toad/c_utils.pyx:18:18: 'number' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  res += arr[i, j]
      
          return res
      
      
      cdef number[:] c_sum_axis_0(number[:,:] arr):
          ^
      ------------------------------------------------------------
      
      toad/c_utils.pyx:29:5: 'number' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  res += arr[i, j]
      
          return res
      
      
      cdef number[:] c_sum_axis_0(number[:,:] arr):
                                 ^
      ------------------------------------------------------------
      
      toad/c_utils.pyx:29:28: 'number' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  res[j] += arr[i, j]
      
          return res
      
      
      cdef number[:] c_sum_axis_1(number[:,:] arr):
          ^
      ------------------------------------------------------------
      
      toad/c_utils.pyx:39:5: 'number' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  res[j] += arr[i, j]
      
          return res
      
      
      cdef number[:] c_sum_axis_1(number[:,:] arr):
                                 ^
      ------------------------------------------------------------
      
      toad/c_utils.pyx:39:28: 'number' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cimport cython
      
      
      
      cdef number c_min(number[:] arr):
          cdef number res = np.inf
              ^
      ------------------------------------------------------------
      
      toad/c_utils.pyx:10:9: 'number' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  res = arr[i]
          return res
      
      
      cdef number c_sum(number[:,:] arr):
          cdef number res = 0
              ^
      ------------------------------------------------------------
      
      toad/c_utils.pyx:19:9: 'number' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          return res
      
      
      cdef number[:] c_sum_axis_0(number[:,:] arr):
          cdef number[:] res = np.zeros(arr.shape[1], dtype=np.float)
              ^
      ------------------------------------------------------------
      
      toad/c_utils.pyx:30:9: 'number' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          return res
      
      
      cdef number[:] c_sum_axis_1(number[:,:] arr):
          cdef number[:] res = np.zeros(arr.shape[0], dtype=np.float)
              ^
      ------------------------------------------------------------
      
      toad/c_utils.pyx:40:9: 'number' is not a type identifier
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-maztxps_/toad_075c85e7ef5d40fba2779405e990bf6f/setup.py", line 59, in <module>
          ext_modules = get_ext_modules(),
        File "/tmp/pip-install-maztxps_/toad_075c85e7ef5d40fba2779405e990bf6f/setup.py", line 27, in get_ext_modules
          return cythonize(extensions)
        File "/opt/conda/envs/default_python3_9_tf_2_9/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
          cythonize_one(*args)
        File "/opt/conda/envs/default_python3_9_tf_2_9/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: toad/c_utils.pyx
      Compiling toad/c_utils.pyx because it depends on /opt/conda/envs/default_python3_9_tf_2_9/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      Compiling toad/merge.pyx because it depends on /opt/conda/envs/default_python3_9_tf_2_9/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.
      [1/2] Cythonizing toad/c_utils.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tzhang** [comment]
I got the same error when install toad with pip in conda env on an apple MacBook Pro M1

**Comment by Secbone** [comment]
@tzhang @momomobinx Could you try to upgrade the `NumPy` and `Cython` versions? Or try to install with conda like:
```
conda install toad --channel conda-forge
```

**Comment by encyc** [comment]
Hello, I had the same error.
Meanwhile, my numpy version is 1.23.3 and cython is 0.29.32. Both of them met the requirement.

**Comment by Secbone** [comment]
@encyc do you use Linux OS? I just found toad missed the Linux version in `0.0.64`

**Comment by encyc** [comment]
> @encyc do you use Linux OS? I just found toad missed the Linux version in `0.0.64` for py39

Hi, I solved it.
Firstly, I downloaded the zip from Qsinghua minor and was warned that c_utils.pxd unfound, so I went here(GitHub) and downloaded the zip directly.
Secondly, I noticed that it is based on Cython and I updated my C++ Build Tools up to version 14.0.0 , restarted the computer, and pip install again. 
Then it was solved. BTW, I am definitely using windows 11.
Thank you very much!

**Comment by momomobinx** [comment]
update NumPy

**Comment by lilhe0712** [comment]
我的MacBook pro m1在更新过cython和numpy之后还是存在同样的问题

**Comment by Secbone** [comment]
@lilhe0712 @javakenny  你们如果是 python3.9 及以上的话，可以尝试下载master的代码再本地安装试试
Duplicated #113

**Comment by duzx1** [comment]
maos m1
本地安装了 toad，就是各种奇怪的报错
ModuleNotFoundError: No module named 'toad.merge'

**Comment by tonyye** [comment]
Ran into this issue on OSX, does anyone have any suggestions?

**Comment by willyoung7077** [comment]
@momomobinx and all,

I think I can end this issue

There are two steps to solve this problem.

Step1：
According to my experiences. This issue only happens on MacOS.
Like Mine: Apple M2/ Platform: osx-arm64

If you're not sure what platform your MacOS is,
uname -a in MacOS Terminal,
Darwin localhost 23.2.0 Darwin Kernel Version 23.2.0 ....  arm64

arm64 is the key point.

There are a lot of things not doing well on osx-arm64, like python 3.7

solution: highly-voted answer
https://stackoverflow.com/questions/70205633/cannot-install-python-3-7-on-osx-arm64

conda create -n py37
conda activate py37
#key code:
conda config --env --set subdir osx-64
conda install python=3.7
The version of python doesn't matter

your osx-arm64 changes to osx-64

Step2:

Do not use pip install toad

still return error

Use conda install toad
add --channel conda-forge or not

will@localhost ~ % conda install toad  --channel conda-forge
Channels:
 - conda-forge
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/will/anaconda3/envs/python38

  added / updated specs:
    - toad


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    brotli-python-1.1.0        |   py38h940360d_1         358 KB  conda-forge
    charset-normalizer-3.3.2   |     pyhd8ed1ab_0          46 KB  conda-forge
    contourpy-1.1.1            |   py38h15a1a5b_1         212 KB  conda-forge
    cycler-0.12.1              |     pyhd8ed1ab_0          13 KB  conda-forge
    fonttools-4.53.0           |   py38hc718529_0         2.1 MB  conda-forge
    idna-3.7                   |     pyhd8ed1ab_0          51 KB  conda-forge
    importlib-resources-6.4.0  |     pyhd8ed1ab_0           9 KB  conda-forge
    importlib_resources-6.4.0  |     pyhd8ed1ab_0          32 KB  conda-forge
    joblib-1.4.2               |     pyhd8ed1ab_0         215 KB  conda-forge
    kiwisolver-1.4.5           |   py38h15a1a5b_1          59 KB  conda-forge
    lcms2-2.16                 |       ha2f27b4_0         219 KB  conda-forge
    libdeflate-1.20            |       h49d49c5_0          69 KB  conda-forge
    libjpeg-turbo-3.0.0        |       h0dc2134_1         566 KB  conda-forge
    libtiff-4.6.0              |       h129831d_3         251 KB  conda-forge
    libxcb-1.16                |       h0dc2134_0         315 KB  conda-forge
    matplotlib-base-3.7.3      |   py38hcd1b199_0         6.4 MB  conda-forge
    numpy-1.24.4               |   py38h9a4a08f_0         6.0 MB  conda-forge
    openjpeg-2.5.2             |       h7310d3a_0         324 KB  conda-forge
    packaging-24.1             |     pyhd8ed1ab_0          49 KB  conda-forge
    pandas-2.0.3               |   py38h78e6021_1        11.0 MB  conda-forge
    pillow-10.3.0              |   py38hf802781_1        39.8 MB  conda-forge
    platformdirs-4.2.2         |     pyhd8ed1ab_0          20 KB  conda-forge
    pooch-1.8.2                |     pyhd8ed1ab_0          53 KB  conda-forge
    pysocks-1.7.1              |     pyha2e5f31_6          19 KB  conda-forge
    python-tzdata-2024.1       |     pyhd8ed1ab_0         141 KB  conda-forge
    python_abi-3.8             |           4_cp38           6 KB  conda-forge
    requests-2.32.3            |     pyhd8ed1ab_0          57 KB  conda-forge
    scikit-learn-1.3.2         |   py38h43a65be_2         7.1 MB  conda-forge
    scipy-1.10.1               |   py38h9cf86d3_3        14.7 MB  conda-forge
    seaborn-0.13.2             |       hd8ed1ab_2           7 KB  conda-forge
    seaborn-base-0.13.2        |     pyhd8ed1ab_2         229 KB  conda-forge
    statsmodels-0.14.1         |   py38h7092abf_0        10.0 MB  conda-forge
    threadpoolctl-3.5.0        |     pyhc1e730c_0          23 KB  conda-forge
    toad-0.1.0                 |   py38hef030d1_2        12.7 MB  conda-forge
    unicodedata2-15.1.0        |   py38hcafd530_0         361 KB  conda-forge
    urllib3-2.2.2              |     pyhd8ed1ab_0          93 KB  conda-forge
    zipp-3.19.2                |     pyhd8ed1ab_0          20 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       113.5 MB

The following NEW packages will be INSTALLED:

  brotli             conda-forge/osx-64::brotli-1.1.0-h0dc2134_1 
  brotli-bin         conda-forge/osx-64::brotli-bin-1.1.0-h0dc2134_1 
  brotli-python      conda-forge/osx-64::brotli-python-1.1.0-py38h940360d_1 
  certifi            conda-forge/noarch::certifi-2024.6.2-pyhd8ed1ab_0 
  charset-normalizer conda-forge/noarch::charset-normalizer-3.3.2-pyhd8ed1ab_0 
  contourpy          conda-forge/osx-64::contourpy-1.1.1-py38h15a1a5b_1 
  cycler             conda-forge/noarch::cycler-0.12.1-pyhd8ed1ab_0 
  fonttools          conda-forge/osx-64::fonttools-4.53.0-py38hc718529_0 
  freetype           conda-forge/osx-64::freetype-2.12.1-h60636b9_2 
  idna               conda-forge/noarch::idna-3.7-pyhd8ed1ab_0 
  importlib-resourc~ conda-forge/noarch::importlib-resources-6.4.0-pyhd8ed1ab_0 
  importlib_resourc~ conda-forge/noarch::importlib_resources-6.4.0-pyhd8ed1ab_0 
  joblib             conda-forge/noarch::joblib-1.4.2-pyhd8ed1ab_0 
  kiwisolver         conda-forge/osx-64::kiwisolver-1.4.5-py38h15a1a5b_1 
  lcms2              conda-forge/osx-64::lcms2-2.16-ha2f27b4_0 
  lerc               conda-forge/osx-64::lerc-4.0.0-hb486fe8_0 
  libblas            conda-forge/osx-64::libblas-3.9.0-20_osx64_openblas 
  libbrotlicommon    conda-forge/osx-64::libbrotlicommon-1.1.0-h0dc2134_1 
  libbrotlidec       conda-forge/osx-64::libbrotlidec-1.1.0-h0dc2134_1 
  libbrotlienc       conda-forge/osx-64::libbrotlienc-1.1.0-h0dc2134_1 
  libcblas           conda-forge/osx-64::libcblas-3.9.0-20_osx64_openblas 
  libcxx             conda-forge/osx-64::libcxx-17.0.6-h88467a6_0 
  libdeflate         conda-forge/osx-64::libdeflate-1.20-h49d49c5_0 
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-13_2_0_h97931a8_3 
  libgfortran5       conda-forge/osx-64::libgfortran5-13.2.0-h2873a65_3 
  libjpeg-turbo      conda-forge/osx-64::libjpeg-turbo-3.0.0-h0dc2134_1 
  liblapack          conda-forge/osx-64::liblapack-3.9.0-20_osx64_openblas 
  libopenblas        conda-forge/osx-64::libopenblas-0.3.25-openmp_hfef2a42_0 
  libpng             conda-forge/osx-64::libpng-1.6.43-h92b6c6a_0 
  libtiff            conda-forge/osx-64::libtiff-4.6.0-h129831d_3 
  libwebp-base       conda-forge/osx-64::libwebp-base-1.4.0-h10d778d_0 
  libxcb             conda-forge/osx-64::libxcb-1.16-h0dc2134_0 
  llvm-openmp        conda-forge/osx-64::llvm-openmp-18.1.8-h15ab845_0 
  matplotlib-base    conda-forge/osx-64::matplotlib-base-3.7.3-py38hcd1b199_0 
  munkres            conda-forge/noarch::munkres-1.1.4-pyh9f0ad1d_0 
  numpy              conda-forge/osx-64::numpy-1.24.4-py38h9a4a08f_0 
  openjpeg           conda-forge/osx-64::openjpeg-2.5.2-h7310d3a_0 
  packaging          conda-forge/noarch::packaging-24.1-pyhd8ed1ab_0 
  pandas             conda-forge/osx-64::pandas-2.0.3-py38h78e6021_1 
  patsy              conda-forge/noarch::patsy-0.5.6-pyhd8ed1ab_0 
  pillow             conda-forge/osx-64::pillow-10.3.0-py38hf802781_1 
  platformdirs       conda-forge/noarch::platformdirs-4.2.2-pyhd8ed1ab_0 
  pooch              conda-forge/noarch::pooch-1.8.2-pyhd8ed1ab_0 
  pthread-stubs      conda-forge/osx-64::pthread-stubs-0.4-hc929b4f_1001 
  pyparsing          conda-forge/noarch::pyparsing-3.1.2-pyhd8ed1ab_0 
  pysocks            conda-forge/noarch::pysocks-1.7.1-pyha2e5f31_6 
  python-dateutil    conda-forge/noarch::python-dateutil-2.9.0-pyhd8ed1ab_0 
  python-tzdata      conda-forge/noarch::python-tzdata-2024.1-pyhd8ed1ab_0 
  python_abi         conda-forge/osx-64::python_abi-3.8-4_cp38 
  pytz               conda-forge/noarch::pytz-2024.1-pyhd8ed1ab_0 
  requests           conda-forge/noarch::requests-2.32.3-pyhd8ed1ab_0 
  scikit-learn       conda-forge/osx-64::scikit-learn-1.3.2-py38h43a65be_2 
  scipy              conda-forge/osx-64::scipy-1.10.1-py38h9cf86d3_3 
  seaborn            conda-forge/noarch::seaborn-0.13.2-hd8ed1ab_2 
  seaborn-base       conda-forge/noarch::seaborn-base-0.13.2-pyhd8ed1ab_2 
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0 
  statsmodels        conda-forge/osx-64::statsmodels-0.14.1-py38h7092abf_0 
  threadpoolctl      conda-forge/noarch::threadpoolctl-3.5.0-pyhc1e730c_0 
  toad               conda-forge/osx-64::toad-0.1.0-py38hef030d1_2 
  unicodedata2       conda-forge/osx-64::unicodedata2-15.1.0-py38hcafd530_0 
  urllib3            conda-forge/noarch::urllib3-2.2.2-pyhd8ed1ab_0 
  xorg-libxau        conda-forge/osx-64::xorg-libxau-1.0.11-h0dc2134_0 
  xorg-libxdmcp      conda-forge/osx-64::xorg-libxdmcp-1.1.3-h35c211d_0 
  zipp               conda-forge/noarch::zipp-3.19.2-pyhd8ed1ab_0 
  zstd               conda-forge/osx-64::zstd-1.5.6-h915ae27_0 

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge/osx-arm64::ca-certificate~ --> conda-forge/osx-64::ca-certificates-2024.6.2-h8857fd0_0 
  openssl            conda-forge/osx-arm64::openssl-3.3.1-~ --> conda-forge/osx-64::openssl-3.3.1-h87427d6_0 


Proceed ([y]/n)? y


Downloading and Extracting Packages:
                                                                                                                                                   
Preparing transaction: done                                                                                                                        
Verifying transaction: done                                                                                                                        
Executing transaction: done          
PS:
As for another setup method：
https://github.com/amphibian-dev/toad

Source code
python setup.py install

I didn't try .

This issue takes me a lot of time to solve it , wish you have a good day , dudes

**Comment by momomobinx** [comment]
> @momomobinx and all,
> 
> I think I can end this issue
> 
> There are two steps to solve this problem.
> 
> Step1： According to my experiences. This issue only happens on MacOS. Like Mine: Apple M2/ Platform: osx-arm64
> 
> If you're not sure what platform your MacOS is, uname -a in MacOS Terminal, Darwin localhost 23.2.0 Darwin Kernel Version 23.2.0 .... arm64
> 
> arm64 is the key point.
> 
> There are a lot of things not doing well on osx-arm64, like python 3.7
> 
> solution: highly-voted answer https://stackoverflow.com/questions/70205633/cannot-install-python-3-7-on-osx-arm64
> 
> conda create -n py37 conda activate py37 #key code: conda config --env --set subdir osx-64 conda install python=3.7 The version of python doesn't matter
> 
> your osx-arm64 changes to osx-64
> 
> Step2:
> 
> Do not use pip install toad
> 
> still return error
> 
> Use conda install toad add --channel conda-forge or not
> 
> will@localhost ~ % conda install toad --channel conda-forge Channels:
> 
> * conda-forge
> * https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> * https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
> * defaults
>   Platform: osx-64
>   Collecting package metadata (repodata.json): done
>   Solving environment: done
> 
> ## Package Plan
> environment location: /Users/will/anaconda3/envs/python38
> 
> added / updated specs: - toad
> 
> The following packages will be downloaded:
> 
> ```
> package                    |            build
> ---------------------------|-----------------
> brotli-python-1.1.0        |   py38h940360d_1         358 KB  conda-forge
> charset-normalizer-3.3.2   |     pyhd8ed1ab_0          46 KB  conda-forge
> contourpy-1.1.1            |   py38h15a1a5b_1         212 KB  conda-forge
> cycler-0.12.1              |     pyhd8ed1ab_0          13 KB  conda-forge
> fonttools-4.53.0           |   py38hc718529_0         2.1 MB  conda-forge
> idna-3.7                   |     pyhd8ed1ab_0          51 KB  conda-forge
> importlib-resources-6.4.0  |     pyhd8ed1ab_0           9 KB  conda-forge
> importlib_resources-6.4.0  |     pyhd8ed1ab_0          32 KB  conda-forge
> joblib-1.4.2               |     pyhd8ed1ab_0         215 KB  conda-forge
> kiwisolver-1.4.5           |   py38h15a1a5b_1          59 KB  conda-forge
> lcms2-2.16                 |       ha2f27b4_0         219 KB  conda-forge
> libdeflate-1.20            |       h49d49c5_0          69 KB  conda-forge
> libjpeg-turbo-3.0.0        |       h0dc2134_1         566 KB  conda-forge
> libtiff-4.6.0              |       h129831d_3         251 KB  conda-forge
> libxcb-1.16                |       h0dc2134_0         315 KB  conda-forge
> matplotlib-base-3.7.3      |   py38hcd1b199_0         6.4 MB  conda-forge
> numpy-1.24.4               |   py38h9a4a08f_0         6.0 MB  conda-forge
> openjpeg-2.5.2             |       h7310d3a_0         324 KB  conda-forge
> packaging-24.1             |     pyhd8ed1ab_0          49 KB  conda-forge
> pandas-2.0.3               |   py38h78e6021_1        11.0 MB  conda-forge
> pillow-10.3.0              |   py38hf802781_1        39.8 MB  conda-forge
> platformdirs-4.2.2         |     pyhd8ed1ab_0          20 KB  conda-forge
> pooch-1.8.2                |     pyhd8ed1ab_0          53 KB  conda-forge
> pysocks-1.7.1              |     pyha2e5f31_6          19 KB  conda-forge
> python-tzdata-2024.1       |     pyhd8ed1ab_0         141 KB  conda-forge
> python_abi-3.8             |           4_cp38           6 KB  conda-forge
> requests-2.32.3            |     pyhd8ed1ab_0          57 KB  conda-forge
> scikit-learn-1.3.2         |   py38h43a65be_2         7.1 MB  conda-forge
> scipy-1.10.1               |   py38h9cf86d3_3        14.7 MB  conda-forge
> seaborn-0.13.2             |       hd8ed1ab_2           7 KB  conda-forge
> seaborn-base-0.13.2        |     pyhd8ed1ab_2         229 KB  conda-forge
> statsmodels-0.14.1         |   py38h7092abf_0        10.0 MB  conda-forge
> threadpoolctl-3.5.0        |     pyhc1e730c_0          23 KB  conda-forge
> toad-0.1.0                 |   py38hef030d1_2        12.7 MB  conda-forge
> unicodedata2-15.1.0        |   py38hcafd530_0         361 KB  conda-forge
> urllib3-2.2.2              |     pyhd8ed1ab_0          93 KB  conda-forge
> zipp-3.19.2                |     pyhd8ed1ab_0          20 KB  conda-forge
> ------------------------------------------------------------
>                                        Total:       113.5 MB
> ```
> 
> The following NEW packages will be INSTALLED:
> 
> brotli conda-forge/osx-64::brotli-1.1.0-h0dc2134_1 brotli-bin conda-forge/osx-64::brotli-bin-1.1.0-h0dc2134_1 brotli-python conda-forge/osx-64::brotli-python-1.1.0-py38h940360d_1 certifi conda-forge/noarch::certifi-2024.6.2-pyhd8ed1ab_0 charset-normalizer conda-forge/noarch::charset-normalizer-3.3.2-pyhd8ed1ab_0 contourpy conda-forge/osx-64::contourpy-1.1.1-py38h15a1a5b_1 cycler conda-forge/noarch::cycler-0.12.1-pyhd8ed1ab_0 fonttools conda-forge/osx-64::fonttools-4.53.0-py38hc718529_0 freetype conda-forge/osx-64::freetype-2.12.1-h60636b9_2 idna conda-forge/noarch::idna-3.7-pyhd8ed1ab_0 importlib-resourc~ conda-forge/noarch::importlib-resources-6.4.0-pyhd8ed1ab_0 importlib_resourc~ conda-forge/noarch::importlib_resources-6.4.0-pyhd8ed1ab_0 joblib conda-forge/noarch::joblib-1.4.2-pyhd8ed1ab_0 kiwisolver conda-forge/osx-64::kiwisolver-1.4.5-py38h15a1a5b_1 lcms2 conda-forge/osx-64::lcms2-2.16-ha2f27b4_0 lerc conda-forge/osx-64::lerc-4.0.0-hb486fe8_0 libblas conda-forge/osx-64::libblas-3.9.0-20_osx64_openblas libbrotlicommon conda-forge/osx-64::libbrotlicommon-1.1.0-h0dc2134_1 libbrotlidec conda-forge/osx-64::libbrotlidec-1.1.0-h0dc2134_1 libbrotlienc conda-forge/osx-64::libbrotlienc-1.1.0-h0dc2134_1 libcblas conda-forge/osx-64::libcblas-3.9.0-20_osx64_openblas libcxx conda-forge/osx-64::libcxx-17.0.6-h88467a6_0 libdeflate conda-forge/osx-64::libdeflate-1.20-h49d49c5_0 libgfortran conda-forge/osx-64::libgfortran-5.0.0-13_2_0_h97931a8_3 libgfortran5 conda-forge/osx-64::libgfortran5-13.2.0-h2873a65_3 libjpeg-turbo conda-forge/osx-64::libjpeg-turbo-3.0.0-h0dc2134_1 liblapack conda-forge/osx-64::liblapack-3.9.0-20_osx64_openblas libopenblas conda-forge/osx-64::libopenblas-0.3.25-openmp_hfef2a42_0 libpng conda-forge/osx-64::libpng-1.6.43-h92b6c6a_0 libtiff conda-forge/osx-64::libtiff-4.6.0-h129831d_3 libwebp-base conda-forge/osx-64::libwebp-base-1.4.0-h10d778d_0 libxcb conda-forge/osx-64::libxcb-1.16-h0dc2134_0 llvm-openmp conda-forge/osx-64::llvm-openmp-18.1.8-h15ab845_0 matplotlib-base conda-forge/osx-64::matplotlib-base-3.7.3-py38hcd1b199_0 munkres conda-forge/noarch::munkres-1.1.4-pyh9f0ad1d_0 numpy conda-forge/osx-64::numpy-1.24.4-py38h9a4a08f_0 openjpeg conda-forge/osx-64::openjpeg-2.5.2-h7310d3a_0 packaging conda-forge/noarch::packaging-24.1-pyhd8ed1ab_0 pandas conda-forge/osx-64::pandas-2.0.3-py38h78e6021_1 patsy conda-forge/noarch::patsy-0.5.6-pyhd8ed1ab_0 pillow conda-forge/osx-64::pillow-10.3.0-py38hf802781_1 platformdirs conda-forge/noarch::platformdirs-4.2.2-pyhd8ed1ab_0 pooch conda-forge/noarch::pooch-1.8.2-pyhd8ed1ab_0 pthread-stubs conda-forge/osx-64::pthread-stubs-0.4-hc929b4f_1001 pyparsing conda-forge/noarch::pyparsing-3.1.2-pyhd8ed1ab_0 pysocks conda-forge/noarch::pysocks-1.7.1-pyha2e5f31_6 python-dateutil conda-forge/noarch::python-dateutil-2.9.0-pyhd8ed1ab_0 python-tzdata conda-forge/noarch::python-tzdata-2024.1-pyhd8ed1ab_0 python_abi conda-forge/osx-64::python_abi-3.8-4_cp38 pytz conda-forge/noarch::pytz-2024.1-pyhd8ed1ab_0 requests conda-forge/noarch::requests-2.32.3-pyhd8ed1ab_0 scikit-learn conda-forge/osx-64::scikit-learn-1.3.2-py38h43a65be_2 scipy conda-forge/osx-64::scipy-1.10.1-py38h9cf86d3_3 seaborn conda-forge/noarch::seaborn-0.13.2-hd8ed1ab_2 seaborn-base conda-forge/noarch::seaborn-base-0.13.2-pyhd8ed1ab_2 six conda-forge/noarch::six-1.16.0-pyh6c4a22f_0 statsmodels conda-forge/osx-64::statsmodels-0.14.1-py38h7092abf_0 threadpoolctl conda-forge/noarch::threadpoolctl-3.5.0-pyhc1e730c_0 toad conda-forge/osx-64::toad-0.1.0-py38hef030d1_2 unicodedata2 conda-forge/osx-64::unicodedata2-15.1.0-py38hcafd530_0 urllib3 conda-forge/noarch::urllib3-2.2.2-pyhd8ed1ab_0 xorg-libxau conda-forge/osx-64::xorg-libxau-1.0.11-h0dc2134_0 xorg-libxdmcp conda-forge/osx-64::xorg-libxdmcp-1.1.3-h35c211d_0 zipp conda-forge/noarch::zipp-3.19.2-pyhd8ed1ab_0 zstd conda-forge/osx-64::zstd-1.5.6-h915ae27_0
> 
> The following packages will be SUPERSEDED by a higher-priority channel:
> 
> ca-certificates conda-forge/osx-arm64::ca-certificate~ --> conda-forge/osx-64::ca-certificates-2024.6.2-h8857fd0_0 openssl conda-forge/osx-arm64::openssl-3.3.1-~ --> conda-forge/osx-64::openssl-3.3.1-h87427d6_0
> 
> Proceed ([y]/n)? y
> 
> Downloading and Extracting Packages:
> 
> Preparing transaction: done Verifying transaction: done Executing transaction: done PS: As for another setup method： https://github.com/amphibian-dev/toad
> 
> Source code python setup.py install
> 
> I didn't try .
> 
> This issue takes me a lot of time to solve it , wish you have a good day , dudes

I also encountered this problem when building the arm version of the docker image. Later, as I posted before closing it, I upgraded NumPy and installed it normally. Thank you for your reply here.

**Comment by zhuzihao-hz** [comment]
> > [@encyc](https://github.com/encyc) do you use Linux OS? I just found toad missed the Linux version in `0.0.64` for py39
> 
> Hi, I solved it. Firstly, I downloaded the zip from Qsinghua minor and was warned that c_utils.pxd unfound, so I went here(GitHub) and downloaded the zip directly. Secondly, I noticed that it is based on Cython and I updated my C++ Build Tools up to version 14.0.0 , restarted the computer, and pip install again. Then it was solved. BTW, I am definitely using windows 11. Thank you very much!

I faced a similar situation. in the debian, py312 docker image, I tried to use the tar.gz downloaded from pypi.org and built the whl but failed. Then I tried the zip package of the master branch, built successful. Thanks!
