### ISSUE TITLE
Transformer类实例化不会初始化类参数

### ISSUE THREAD

**Issue by Ausar0109** [amphibian-dev/toad#11]
combiner = toad.transform.Combiner()
combiner.fit(......)
print(combiner.export())
-------------------------------
{'a':[1,2,3,4,5]}

combiner2 = toad.transform.Combiner()
print(combiner2.export())
-------------------------------
{'a':[1,2,3,4,5]}

combiner2 是一个新的实例，没做任何input,确因为继承父类的原因，和combiner共享部分数据

**Comment by Ausar0109** [comment]
实例化combiner的时候，能修改为给一个全新的对象吗

**Comment by Secbone** [comment]
@Ausar0109   我这边没有复现你说的情况，你使用的版本是多少？可以通过 `toad.__version__` 查看

**Comment by Ausar0109** [comment]
后面没有出现这种问题了，我也不清楚之前为啥

**Comment by Secbone** [comment]
@Ausar0109 多谢反馈，有其他问题欢迎随时反馈~  :smiley:
