### ISSUE TITLE
combiner的n_bins问题

### ISSUE THREAD

**Issue by lokihu** [amphibian-dev/toad#12]
设置n_bins = 5 结果分了12箱。

`combiner = toad.transform.Combiner()

combiner.fit(dev_slct2,dev_slct2['target'],method='chi',min_samples = 0.05,n_bins = 5,
             exclude=ex_lis) 

bins = combiner.export() 

bins['age']`

> [22, 23, 25, 26, 27, 28, 31, 33, 35, 38, 43]

**Comment by Secbone** [comment]
@lokihu 这里是因为触发了 min_samples 的条件，如果你希望指定分 5 组，可以去掉 min_samples 参数.
