### ISSUE TITLE
Public Datasets

### ISSUE THREAD

**Issue by assiswagner** [amphibian-dev/toad#125]
Look like an awesome package. But would be better if you could provide the datasets used in tutorials for reproducibility.
For instance, I can't find the same "germancredit.csv" used in "complete tutorial.ipynb" (there is a tons of different versions).
Could you please share the file or link?
Regards,
Wagner Assis

**Comment by Secbone** [comment]
link: https://pan.baidu.com/s/1rIaQm0XunlBU_5YXt6CXBw 
token: fma6

duplicated with #31
