### ISSUE TITLE
分箱用不了toad.merge.DTMerge()

### ISSUE THREAD

**Issue by kyle-pjk** [amphibian-dev/toad#15]
所有的toad.merge的函数都没法用
![image](https://user-images.githubusercontent.com/56810256/76275562-9026ed80-62be-11ea-9a4f-07550c83866f.png)

**Comment by Secbone** [comment]
@kyle-pjk  `toad.merge` 目前是被绑定为 `toad.merge.merge` 的快捷链接，你如果要使用 `DTMerge` 的话，可以
```python
from toad.merge import DTMerge
DTMerge()
```
或者使用快捷链接
```python
toad.merge(xxxx, method = 'dt')
```

**Comment by kyle-pjk** [comment]
@Secbone 尴尬了，thx

**Comment by Secbone** [comment]
@kyle-pjk 有其他问题欢迎随时反馈~  :smiley:
