### ISSUE TITLE
评分卡输出的分数跟单独跑一条的分数对不上

### ISSUE THREAD

**Issue by kyle-pjk** [amphibian-dev/toad#16]
![image](https://user-images.githubusercontent.com/56810256/77145625-08ae5b00-6ac4-11ea-8cd9-9bb6c0429687.png)
我单独拿dataframe第1行的数据去predict，分数是482分，但是整个dataframe predict出来的第一个数是506分

**Comment by kyle-pjk** [comment]
![image](https://user-images.githubusercontent.com/56810256/77146152-5aa3b080-6ac5-11ea-93fb-0cfdc0a3c6e6.png)

**Comment by kyle-pjk** [comment]
@Secbone 辛苦大佬

**Comment by kyle-pjk** [comment]
![image](https://user-images.githubusercontent.com/56810256/77146955-377a0080-6ac7-11ea-98dd-b13beb2580fa.png)
第一列是整个dataframe 预测出来的分数，第二列是我一条一条预测的分数

**Comment by kyle-pjk** [comment]
![image](https://user-images.githubusercontent.com/56810256/77150587-2c2ad300-6acf-11ea-85f7-ae6f36f19847.png)
好像找到了问题，predict的时候会因为数据类型改变而导致结果发生变化

**Comment by Secbone** [comment]
@kyle-pjk 数据类型改变是指哪里的改变？
方便把 `scorecard.export()` 出来看一下么？

**Comment by kyle-pjk** [comment]
就是训练集类型是str，即['True','False','NAN'],然后我单独跑一个用户的时候，就读成了False，两个的类型不一致，导致最终分数不一样
