### ISSUE TITLE
在对带有缺失值的连续型数据调整分箱的时候无法正常运作

### ISSUE THREAD

**Issue by lijanqing** [amphibian-dev/toad#17]
您好，我在对带有缺失值的连续型变量分箱的时候，先是把缺失单独分成一箱，然后再进行分箱调整的时候发现name 'nan' is not defined的问题，导致无法正常分箱，请问如何处理这个问题？

**Comment by Secbone** [comment]
@lijanqing 有详细一点儿的代码 和 报错提示么？

**Comment by lijanqing** [comment]
我的变量名为’v1‘,是一个float类型，且有缺失值的变量。
下面是通过卡方分箱后分到的结果：
col='v1'
c.export()[col]
Out[394]: [5.0, 7.0, 17.0, 79.0, nan]
然后我开始想要把nan分到其他箱子内，我开始用以下代码：
col='v1'
rule = {col:[5.0, 7.0, 17.0, 79.0, nan]}
Traceback (most recent call last):

  File "<ipython-input-403-dff2ba4327f3>", line 2, in <module>
    rule = {col:[5.0, 7.0, 17.0, 79.0, nan]}

NameError: name 'nan' is not defined
请问这里的nan该怎么处理？

**Comment by lijanqing** [comment]
我找到方法了，就是把nan变更为np.nan，但是这还是没有达到将nan的箱和其他已经分好的连续型变量箱子指定一箱合并（分类变量这个问题可以解决）。请问如何操作？

**Comment by Secbone** [comment]
@lijanqing 连续型数据的分箱区间是 `-inf` 到 `inf` 的，所以如果你希望把空值合并进某一组的话，直接将空值数据替换成对应组的数值就可以了（`combiner` 会默认将空值替换成 `-1`）

**Comment by xingxiang2018** [comment]
> @lijanqing 连续型数据的分箱区间是 `-inf` 到 `inf` 的，所以如果你希望把空值合并进某一组的话，直接将空值数据替换成对应组的数值就可以了（`combiner` 会默认将空值替换成 `-1`，即对应你的分箱就是 `-inf ~ 5.0` 这一组）

聪明，明白你的意思。
