### ISSUE TITLE
Why doesn't it need bins when selecting features? 

### ISSUE THREAD

**Issue by Hala2Madrid** [amphibian-dev/toad#27]
I am confused with the feature selection process in your tutorial.
How do toad.quality & toad.selection.select calculate information values? Don't they need bins? 
Thanks.

**Comment by Secbone** [comment]
@Hala2Madrid When calculate the information value, the `IV` function will automate bin the data to 10 groups using `decision tree` (when the data have more than 10 unique values). It also works in `toad.quality` and `toad.selection.select`

**Comment by Hala2Madrid** [comment]
I see. Thank you. Can I use other bins when toad.quality or toad.selection.select?

**Comment by Secbone** [comment]
@Hala2Madrid `toad.quality` support `n_bins` and `method` arguments for changing the number of groups or the combine method, but `toad.selection.select` has not support it now, but you can use `Combiner` to transform your data before using `select`.

**Comment by Hala2Madrid** [comment]
Thank you!
