### ISSUE TITLE
Is it ok to adjust your bins depending on bad rate plot including test data set?

### ISSUE THREAD

**Issue by Hala2Madrid** [amphibian-dev/toad#28]
As the title of this issue, I am curious about it. Will it introduce future data?

**Comment by Secbone** [comment]
@Hala2Madrid It just a example for `badrate_plot`, it doesn't mean we actually do this step in our works. But it is a way to help us to explain the result when the bins is not good enough.
And I think it is indeed having a bit of misleading, thank you for mention it, I will change it later. 😄

**Comment by onefless** [comment]
@Hala2Madrid It is a common practice in industry to consult out-of-time data to make adjustment accordingly.  In this way, model developers want to guarantee that the boundaries are stable across time. It is not the same as using future data for training.

**Comment by Hala2Madrid** [comment]
Thanks a lot!
