### ISSUE TITLE
Which data should we put into toad.ScoreCard, original data or woe-transformed data?

### ISSUE THREAD

**Issue by Hala2Madrid** [amphibian-dev/toad#29]
In your tutorial, I found that you put woe-transformed data into toad.ScoreCard.
If it needs woe-transformed data, I think it is no need to set the params "combiner" & "transer", is it?
So I think it is designed for the original data, however, in your tutorial, you put final_data in it (see at Block 22) , which is woe-transformed in Block 15.
As a result, I also tried to put woe-transformed data in it, and got a AUC 0.52, further more, I found almost predicted score are the same. 
That's why I raise this issue.
Thanks.

**Comment by Secbone** [comment]
@Hala2Madrid Sorry the tutorial is not completely. It is designed for the original data, but in the `fit` step, you already have the woe data, so we don't need to do it again, so I use the woe data for fitting. But in `predict` step, you can use the original data, and that is why your predicted scores are all the same, the data will be combined and transformed to woe before predict in `ScoreCard`.

**Comment by Hala2Madrid** [comment]
You mean \`fit\` with the woe data but \`predict\` with the original data? That is weird. How can I know if the \`fit\` step, the function will not combine and transform the woe data again?

**Comment by Secbone** [comment]
@Hala2Madrid That looks a bit weird, but it is the quickest way in the workflow of building a scorecard. I will add a more complete example to the tutorial and add some comments to explain it.

Maybe when the workflow is more automatic and does not need to check and bin data by a human, I think the `fit` step can receive origin data at that time.

**Comment by Hala2Madrid** [comment]
I see. Thank you. If you update your tutorial, pls ping me, and I will close this issue.
