### ISSUE TITLE
Gini in quality

### ISSUE THREAD

**Issue by Mateko** [amphibian-dev/toad#33]
Gini returns bad values, its returns 42-43 for all variables (checked on binned, and non binned values)

**Comment by Secbone** [comment]
@Mateko Could you supply a case for more details?

**Comment by Mateko** [comment]
@Secbone I'm trying to test my data, while IV values ​​seem like my function, then gini only returns values ​​from (42-43) for all variables in the dataset - which is definitely wrong.

**Comment by Secbone** [comment]
@Mateko the gini value is depends on data, so you can't say "the values is between 42 and 43" is wrong, could you supply a case, so we can find out if it is wrong?

**Comment by Mateko** [comment]
![unknown](https://user-images.githubusercontent.com/36420445/84025844-8891e600-a98c-11ea-96e8-b4e373450d79.png)
Its looking like constat value, but is not, how the variable with 0.04 IV could have 43 gini?? 
I probably don't understand something

**Comment by Secbone** [comment]
@Mateko  the gini value's formula in `quality` is  ![formula](https://render.githubusercontent.com/render/math?math=\sum_{i}^{n}%20p(x_{i})\cdot%20Gini(x_{i})), which is to use to measure the correlation between the feature and the target, you can see the order of values in your result, the higher the gini value is, the more useless the feature is.

**Comment by Mateko** [comment]
If corellation between feature and default its higher then this feature should be more usefull.

**Comment by Secbone** [comment]
@Mateko Yes, you can think the gini value as the negtive correlation value.

**Comment by Mateko** [comment]
So u think its good to named it Gini in this place? Maybe be better to get there a default % and get a roc auc score from this?

**Comment by Secbone** [comment]
@Mateko Of course it is Gini. The ROC or AUC usually used in binary classification as model metrics, but in this place, it need a value to measure features in many cases, not only binary. 
So I think Gini in this palce is not bad at least.
