### ISSUE TITLE
中文教程里的评分卡参数貌似写反了？

### ISSUE THREAD

**Issue by kyle-pjk** [amphibian-dev/toad#34]
![image](https://user-images.githubusercontent.com/56810256/83860487-e686b980-a751-11ea-93d9-295b0c84b769.png)
![image](https://user-images.githubusercontent.com/56810256/83860591-09b16900-a752-11ea-8627-be483b65bd1b.png)
![image](https://user-images.githubusercontent.com/56810256/83860616-1209a400-a752-11ea-8d50-36502876069b.png)

pdo和base_odds写反了把？

**Comment by Secbone** [comment]
@kyle-pjk 抱歉，中文教程里的描述确实有问题，会尽快更正！
