### ISSUE TITLE
Processing运行报错

### ISSUE THREAD

**Issue by kyle-pjk** [amphibian-dev/toad#35]
![image](https://user-images.githubusercontent.com/56810256/84115306-6f5a6980-aa60-11ea-9f2d-8537aafca09c.png)
![image](https://user-images.githubusercontent.com/56810256/84115325-7aad9500-aa60-11ea-9e6d-17bf96cc35f7.png)
我照着demo写的，不知道为什么会报错AttributeError: 'TimePartition' object has no attribute 'apply'，我import了下面这两条
from toad.preprocessing.partition import *
from toad.preprocessing.process import Processing

**Comment by kyle-pjk** [comment]
@Secbone 麻烦抽空答复下哈

**Comment by kyle-pjk** [comment]
我的toad版本是0.0.60

**Comment by zhouxiyu** [comment]
这是个BUG…下个版本修复…不好意思

**Comment by Secbone** [comment]
@kyle-pjk 最新内测版已发布，可以运行
`pip install toad==0.0.60a0` 安装使用哈
