### ISSUE TITLE
导入时出错

### ISSUE THREAD

**Issue by concertine** [amphibian-dev/toad#36]
你好，我在导入toad库时报错了，请问应该怎么解决？
<img width="578" alt="微信图片_20200615141545" src="https://user-images.githubusercontent.com/66932105/84624025-23ea0480-af13-11ea-9aba-f06c1de911aa.png">

**Comment by Secbone** [comment]
@concertine  更新下 `numpy` 和 `cython` 再试试。
再问一下，你是通过什么方式安装的？ 是离线包安装的么？

**Comment by concertine** [comment]
> @concertine 更新下 `numpy` 和 `cython` 再试试。
> 再问一下，你是通过什么方式安装的？ 是离线包安装的么？

非常感谢！解决了。更新numpy之后在jupyter导入仍然报错，但在Spyder里面可以导入。重启jupyter之后可以正常导入了，谢谢。
我是在Anaconda Prompt里通过pip install命令安装的。

**Comment by Secbone** [comment]
好的，多谢反馈！
