### ISSUE TITLE
ChiMerge函数源代码里没有卡方分布的分位点设置，那分箱的原理是什么？

### ISSUE THREAD

**Issue by concertine** [amphibian-dev/toad#41]
你好，请教一下ChiMerge函数卡方分箱的原理，我看源代码里面没有涉及到卡方分布的自由度、分位点，和论文《ChiMerge: Discretization of Numeric Attributes》（Randy Kerber，1992）的原理不一样？

**Comment by Secbone** [comment]
@concertine  论文中提及的 `自由度` 与 `分位点` 是为了确定最终的 `threshold` 的值，你可以通过 `min_threshold` 参数传入使用。
从应用角度来看，`threshold` 的方式不及 `n_bins` 或 `min_samples` 的方式直观可控，推荐使用 `min_samples` 参数。
