### ISSUE TITLE
请教3个问题

### ISSUE THREAD

**Issue by lijanqing** [amphibian-dev/toad#47]
1、在用toad.quality()计算特征IV值的时候是是基于哪个分箱的依据的，若希望在按照指定要求分箱并计算WOE后再计算出特征的IV值如何操作？
2、在上一步的基础上对每个特征分箱后能否用分箱号替换特征值，而不仅仅用WOE替换特征值？
3、在用toad分箱的时候是否需要考虑分类变量和连续性变量分别分箱，尤其是像身份证所在省份这样类别特别多的分类变量怎么样和连续性变量进行区分？

**Comment by Secbone** [comment]
@lijanqing `quality` 函数默认的分箱方法是使用决策树分箱，默认分10箱。

其他三个问题基本都是关于分箱的，我调整顺序回答你一下：

- (3) toad 中 `Combiner` 模块是负责分箱操作的，toad 中几乎所有的分箱都是依赖它来完成的。 `Combiner` 在分箱时会对 类别型变量 首先进行 `WOE`  编码排序，然后进行相似合并，所以基本不需要考虑分别分箱

- (2) `Combiner` 默认输出就是分箱编号，从 0 开始，当然也可以使用 `labels` 参数输出分箱内容，详情可以查看一下文档

- (1) 如果你希望使用特殊分箱策略进行分箱再计算 `IV`，目前有两种方式可以实现：
    - `quality` 函数支持传入 `method`, `n_bins` 等参数控制分箱策略，参数同 `Combiner`，参考文档看一下
    - 如果你希望可以手动调整某些特殊分箱，可以使用 `Combiner` 对数据进行分箱，然后将分箱好的数据送进 `quality` 函数中进行 `IV` 计算

希望对你有帮助~  😄
