### ISSUE TITLE
处理好的combiner和transer 如何保存和加载，方便模型部署后不需要重新fit_transform

### ISSUE THREAD

**Issue by softdzx** [amphibian-dev/toad#5]
combiner = Combiner()
bins = combiner.fit_transform(df, target, n_bins = 5)
transer = WOETransformer()
woe = transer.fit_transform(bins, target)

如何对combiner和transer 进行保存，方便下次直接进行数据的transform
card = ScoreCard(
    combiner = combiner,
    transer = transer,
)

**Comment by softdzx** [comment]
transer = toad.transform.WOETransformer()
  train_data_woe = transer.fit_transform(binned_data, binned_data[train_target], exclude=[train_target, 'type'])

如何将分箱的binned_data 或bins 变成一个WOETransformer，直接供部署的时候调研WOETransformer

**Comment by Secbone** [comment]
@softdzx 生成的 `card` 可以直接被使用，在生成的时候，`ScoreCard` 生成时，会把 `combiner` 和 `transer` 的信息转换成评分卡，你可以通过 `card.export()` 看到。
同样，`Combiner` 和 `WOETransformer` 也实现了 `export()` 方法，你也可以通过查看具体里面的实现规则。
如果你们一定要分开部署的话，也考虑 `export(to_json = 'xxx.json')` 生成 JSON 格式文件，供研发同学使用。
不知道是不是可以解决你们的问题？

**Comment by Secbone** [comment]
@softdzx 另外一点，可以调用 `Combiner.set_rules()` 方法来载入之前的分箱规则，但是 `WOETransformer` 暂时还没有实现，我会在下一版增加这个功能，非常感谢你的反馈！

**Comment by softdzx** [comment]
非常感谢你的及时回复
ScoreCard 和 Combiner加载 json的规则已经看到了，期待你实现WOETransformer 加载export  后的str类型的json规则，方便模型训练和部署分开部署时的灵活控制

**Comment by Secbone** [comment]
@softdzx  刚发布了 `0.0.59a2` 版本，支持 `WOETransformer` 和 `Combiner` 均支持 `load` 和 `export` 方法
```python
transer.export(to_json = 't.json')
...
transer = WOETransformer().load(from_json = 't.json')
```
可以使用如下命令更新使用
```
pip install -U toad==0.0.59a2
```
如有问题欢迎反馈，正式版发布后会关闭本条 issue~
