### ISSUE TITLE
'bool' object has no attribute 'sum'

### ISSUE THREAD

**Issue by zhaozhongfeng1990** [amphibian-dev/toad#53]
c=(arr==value).sum

**Comment by Secbone** [comment]
@zhaozhongfeng1990 any more details?

**Comment by zhangyanfirez** [comment]
我也遇到了这个问题：
\toad\utils\func.py in np_count(arr, value, default)
     55 
     56 def np_count(arr, value, default = None):
---> 57     c = (arr == value).sum()
     58 
     59     if default is not None and c == 0:

AttributeError: 'bool' object has no attribute 'sum'

**Comment by Secbone** [comment]
@zhangyanfirez  有更多的报错信息么？调用哪个方法的时候报错的？怎么调用的？

**Comment by zhangyanfirez** [comment]
@Secbone   目前已经解决了。问题是使用了pyspark的toPandas()将pyspark的dataframe转换为pandas dataframe后调用了toad.selection.select时报错，原因是(arr == value).sum()中的arr要求是numpy array 。重新使用pandas读取数据后再调用toad.selection.select没有出现问题。
