### ISSUE TITLE
c_utils.pyx 出现 'number' is not a type identifier错误

### ISSUE THREAD

**Issue by penspencap** [amphibian-dev/toad#54]
在安装的时候
![image](https://user-images.githubusercontent.com/25994819/89624525-f2fdce80-d8c8-11ea-8822-d205688ea0eb.png)
![image](https://user-images.githubusercontent.com/25994819/89624543-f85b1900-d8c8-11ea-9a3e-a21f2b179ba8.png)
cython版本 0.29.21 python版本3.6.5 numpy版本1.18.5

**Comment by Secbone** [comment]
@penspencap 建议换官方源或清华源安装哈

**Comment by penspencap** [comment]
还是不行, 有推荐的依赖包的版本吗? 以及知道出现这个问题的原因吗?

**Comment by Secbone** [comment]
@penspencap  你再重新检查一下你的环境吧，错误显示你的 python 版本是 3.8，跟你说的版本不符，所以我现在觉得你之前提供的依赖包可能也是错的，所以你再检查一下环境吧

**Comment by encyc** [comment]
我也遇到了同样的问题，我的版本是python 3.10，版本检查了没有问题。也是cython和numpy的import失败。请问怎么处理呀？
