### ISSUE TITLE
toad.metrics.KS_bucket(pred_train, final_data['target'], bucket=10, method = 'quantile')的结果与示例不一致（0.061版本），与0.060的一致

### ISSUE THREAD

**Issue by xiamuyuan** [amphibian-dev/toad#56]

**Comment by Secbone** [comment]
@xiamuyuan KS_bucket 代码在 0.0.61 版本并没有改动，能提供一个测试样例么？

**Comment by xiamuyuan** [comment]
你好，0.061文档示例的结果表头有这些字段，

cum_bads | cum_goods | cum_total | cum_bads_prop | cum_goods_prop
-- | -- | -- | -- | --

实践下来没有这些，是如下

cum_bad_rate | cum_bad_rate_rev | cum_bads_prop | cum_bads_prop_rev | cum_goods_prop | cum_goods_prop_rev

**Comment by Secbone** [comment]
@xiamuyuan 抱歉，这部分文档还没有更新。这一部分内容是在 0.0.60 版本更新的，添加了一些反向累计的指标，方便直接计算。0.0.60 的版本日志里也有写到。
后续会更新一下文档，与当前版本保持一致。

**Comment by xiamuyuan** [comment]
了解了，谢谢，通过变更包的版本为0.0.59获得了我想要的结果
