### ISSUE TITLE
from toad.plot import badrate_plot, proportion_plot 模块报错

### ISSUE THREAD

**Issue by kanong888** [amphibian-dev/toad#6]
>>> from toad.plot import badrate_plot, proportion_plot
Traceback (most recent call last):
  File "D:\program\Anaconda\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

更新numpy 版本未解决>>> numpy.__version__
'1.18.0'

**Comment by Secbone** [comment]
@kanong888 更新下 `matplotlib` 试下

**Comment by IronMAN3zz** [comment]
更新了matplotlib还是不行

**Comment by kanong888** [comment]
折腾了一圈，更新了numpy、matplotlib、seaborn 都没搞定，最终卸载了 重新安装了官网截止2019年12月最新版本的Anaconda解决了问题（之前用的版本是截止2018年10月的版本官网版本）。暂时没时间回溯定位问题，遇到同样问题的朋友欢迎共享出来  ：）

**Comment by Secbone** [comment]
@kanong888 10月的版本是指 56 还是 57 版本？

**Comment by Secbone** [comment]
定位问题为 seaborn 与 numpy 的兼容问题，已在最新依赖修复。
