### ISSUE TITLE
import toad报错，ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by miaochangq** [amphibian-dev/toad#64]
toad和依赖包已经正确安装：
`Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: toad in /home/mcq/anaconda3/lib/python3.8/site-packages (0.0.63)
Requirement already satisfied: numpy<1.20,>=1.18.0 in /home/mcq/anaconda3/lib/python3.8/site-packages (from toad) (1.19.5)
Requirement already satisfied: scikit-learn>=0.21 in /home/mcq/anaconda3/lib/python3.8/site-packages (from toad) (0.23.1)
Requirement already satisfied: joblib>=0.12 in /home/mcq/anaconda3/lib/python3.8/site-packages (from toad) (0.16.0)
Requirement already satisfied: pandas in /home/mcq/anaconda3/lib/python3.8/site-packages (from toad) (1.0.5)
Requirement already satisfied: seaborn>=0.10.0 in /home/mcq/anaconda3/lib/python3.8/site-packages (from toad) (0.10.1)
Requirement already satisfied: scipy in /home/mcq/anaconda3/lib/python3.8/site-packages (from toad) (1.5.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/mcq/anaconda3/lib/python3.8/site-packages (from scikit-learn>=0.21->toad) (2.1.0)
Requirement already satisfied: python-dateutil>=2.6.1 in /home/mcq/anaconda3/lib/python3.8/site-packages (from pandas->toad) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /home/mcq/anaconda3/lib/python3.8/site-packages (from pandas->toad) (2020.1)
Requirement already satisfied: matplotlib>=2.1.2 in /home/mcq/anaconda3/lib/python3.8/site-packages (from seaborn>=0.10.0->toad) (3.2.2)
Requirement already satisfied: six>=1.5 in /home/mcq/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas->toad) (1.15.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/mcq/anaconda3/lib/python3.8/site-packages (from matplotlib>=2.1.2->seaborn>=0.10.0->toad) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/mcq/anaconda3/lib/python3.8/site-packages (from matplotlib>=2.1.2->seaborn>=0.10.0->toad) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /home/mcq/anaconda3/lib/python3.8/site-packages (from matplotlib>=2.1.2->seaborn>=0.10.0->toad) (0.10.0)`
import 时报错
`

import toad
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-1831ec789c33> in <module>
----> 1 import toad

~/anaconda3/lib/python3.8/site-packages/toad/__init__.py in <module>
----> 1 from .merge import merge, DTMerge, ChiMerge, StepMerge, QuantileMerge, KMeansMerge
      2 from .detector import detect
      3 from .metrics import KS, KS_bucket, F1
      4 from .stats import quality, IV, VIF, WOE, entropy, entropy_cond, gini, gini_cond
      5 from .selection import select

~/anaconda3/lib/python3.8/site-packages/toad/merge.pyx in init toad.merge()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

**Comment by Secbone** [comment]
@miaochangq 更新 numpy 到 1.20以上 或者更新 toad 到 0.0.64a4 可以修复。。。

**Comment by miaochangq** [comment]
我尝试进行了更新，更新numpy的时候，报错如下：
![image](https://user-images.githubusercontent.com/24874881/110441074-53215100-80f4-11eb-86fc-5563fa3fc3b3.png)
我也尝试卸载toad后更新numpy，完成后再安装toad，会将我已经安装好的numpy1.20.1降级
另外我没有办法找到0.0.64a4

**Comment by Secbone** [comment]
@miaochangq  尝试运行 `pip install -U toad==0.0.64a4` 试一下，这个问题会在近期发布新版本修复

**Comment by miaochangq** [comment]
解决了，谢谢您。另外能拉一下我进交流群不，微信mcq123，谢谢。

**Comment by Secbone** [comment]
@miaochangq 微信号没有搜索到，有其他添加方式么？

**Comment by miaochangq** [comment]
> @miaochangq 微信号没有搜索到，有其他添加方式么？

麻烦您再试一下
