### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'sum' 

### ISSUE THREAD

**Issue by ChenTaHung** [amphibian-dev/toad#71]
您好，執行toad.quality時
`toad.quality(train, target = "Attrition", iv_only = True)`
我嘗試過將`in_only = True` 或是 `iv_only = False` ，皆出現了以下的錯誤訊息:
> Traceback (most recent call last):
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 431, in _process_worker
>     r = call_item()
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 285, in __call__
>     return self.fn(*self.args, **self.kwargs)
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
>     return self.func(*args, **kwargs)
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\joblib\parallel.py", line 262, in __call__
>     return [func(*args, **kwargs)
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
>     return [func(*args, **kwargs)
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\toad\stats.py", line 325, in column_quality
>     res[func.name] = func(bin_feature, target)
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\toad\utils\decorator.py", line 32, in __call__
>     return self.wrapper(*args, **kwargs)
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\toad\stats.py", line 278, in wrapper
>     return self.call(*args, **kwargs)
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\toad\utils\decorator.py", line 61, in call
>     return self._fn(*args, **kwargs)
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\toad\utils\decorator.py", line 32, in __call__
>     return self.wrapper(*args, **kwargs)
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\toad\utils\decorator.py", line 126, in wrapper
>     return self.call(frame, *args, **kwargs)
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\toad\utils\decorator.py", line 61, in call
>     return self._fn(*args, **kwargs)
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\toad\stats.py", line 215, in IV
>     iv, sub = _IV(feature, target)
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\toad\stats.py", line 191, in _IV
>     y_prob, n_prob = probability(target, mask = (feature == v))
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\toad\stats.py", line 147, in probability
>     counts_0 = np_count(target, 0, default = 1)
>   File "C:\Users\ydnc\Anaconda3\lib\site-packages\toad\utils\func.py", line 57, in np_count
>     **c = (arr == value).sum()**
> AttributeError: 'bool' object has no attribute 'sum'

我覺得是 `(arr == value).sum()` 這邊沒有辦法對回傳的單一boolean結果加總。

以下是我執行的一些相關版本紀錄:
python version : `Python 3.8.5`
Package version:

> Name: toad
> Version: 0.0.64
> Summary: Toad is dedicated to facilitating model development process, especially for a scorecard.
> Home-page: https://github.com/amphibian-dev/toad
> Author: ESC Team
> Author-email: secbone@gmail.com
> License: MIT

我使用的資料集是網路上的IBM Employee-Attrition.csv，reference link : [IBM HR Analytics Employee Attrition & Performance](https://www.kaggle.com/pavansubhasht/ibm-hr-analytics-attrition-dataset)

請問怎麼解決呢? 謝謝。

**Comment by Secbone** [comment]
@ChenTaHung `toad.quality` 函數只支持 `target` 類型是 `int` 或者 `bool`，你的資料集的 `Attrition` 是字符類型，需要轉換一下
```python
train['target'] = train['Attrition'] == 'Yes'
```
轉換之後再用 `target` 試試

**Comment by ChenTaHung** [comment]
This worked! Thank you!
