### ISSUE TITLE
如何加载已有评分卡

### ISSUE THREAD

**Issue by Tc-blip** [amphibian-dev/toad#78]
我使用了 card.export(to_json=“1.json”)
我如何再次加载这个评分卡 去使用它预测其他数据

**Comment by Secbone** [comment]
@Tc-blip 通过 `card.load(from_json="1.json")` 就可以加载使用了

**Comment by Tc-blip** [comment]
> @Tc-blip 通过 `card.load(from_json="1.json")` 就可以加载使用了

感谢🙏
