### ISSUE TITLE
分箱时对空值如何处理的？源码中没有找到...

### ISSUE THREAD

**Issue by IronMAN3zz** [amphibian-dev/toad#9]
如题，toad会把空值分在第0箱中，希望能单独处理缺失值成一箱而不是和其他箱合并。

**Comment by Ausar0109** [comment]
你把空值填充成-100，再把分箱点第一点手动设定成 -50
那么【-inf,-50】就是你空值的这一箱

python里面 cut_bins 不好对非numbic 的series进行分组，用上面的思路替代解决

**Comment by Secbone** [comment]
@IronMAN3zz 目前数值型的变量，默认分箱会填充为 -1，后续版本会更新空置单独分箱

**Comment by Secbone** [comment]
@IronMAN3zz  刚发布了 `0.0.59a2` 版本，支持空值单独处理
```
Combiner().fit(X, y, empty_separate = True)
```
可以使用如下命令更新使用
```
pip install -U toad==0.0.59a2
```
如有问题欢迎反馈，正式版发布后会关闭本条 issue~

**Comment by IronMAN3zz** [comment]
@Secbone 按照您发的命令无法找到0.0.59a2这个版本，感谢大佬的回复

**Comment by Secbone** [comment]
@IronMAN3zz 是官方源么？ 非官方源可能有延迟
