### ISSUE TITLE
分箱Combiner在训练集上训练后，无法使用至无标签的测试集上

### ISSUE THREAD

**Issue by siri-ya** [amphibian-dev/toad#90]
由于测试集没有标签，直接使用combiner.transform会报错："['label'] not in index"
尝试了增加exclude='label'参数，但仍旧会报错，且该参数在训练时（fit时）无法加入，所以它必须要求训练数据带有标签...
请问这一问题怎么处理？谢谢！

**Comment by Secbone** [comment]
@siri-ya 有数据样例么？没太理解你说的没有标签是什么意思？

**Comment by siri-ya** [comment]
嗯嗯，代码样例是这样：
c = toad.transform.Combiner()
# toBinedData：需要被分箱的训练集数据，标签为'label'列
c.fit(toBinedData,y='label',method='chi',min_samples=0.05)
# bined_trn：分箱后的训练集数据
binned_trn = c.transform(toBinedData,exclude='label')
# toBined_tst：需要被分箱的测试集，由于无标签（需要模型预测），它们没有label这一列
binned_tst = c.transform(toBined_tst,exclude='label')

我后面发现，是我前面的处理问题，toBined_tst可以不包含label列，运行是没有问题的，不好意思打扰啦！

Secbone ***@***.***> 于2021年12月5日周日 下午9:49写道：
